apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
  namespace: jenkins
spec:
  rules:
  - host: jenkins.local
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: http
        pathType: ImplementationSpecific